#!/bin/bash

function check-builtin {
  local command="$1" esc='(\[[ -?]*[@-~])*'
  grc --color --exclude=./test "(^|[^/])\b$command\b" |
    grep -Ev "^$esc([^[:space:]]$esc)+[[:space:]]*#|(\b|$esc)builtin$esc([[:space:]]$esc)+$command(\b|$esc)"
}

# check-builtin echo
# check-builtin printf
# check-builtin eval

function check-bash300bug {
  echo "--- $FUNCNAME ---"
  # bash-3.0 では local arr=(1 2 3) とすると
  # local arr='(1 2 3)' と解釈されてしまう。
  grc 'local [a-zA-Z_]+=\(' --exclude=test
  echo
}

function check-bash301bug-array-element-length {
  echo "--- $FUNCNAME ---"
  # bash-3.1 で ${#arr[index]} を用いると、
  # 日本語の文字数が変になる。
  grc '\$\{#[[:alnum:]]+\[[^@*]' --exclude=test
  echo
}

check-bash300bug
check-bash301bug-array-element-length
